# Generated by Django 4.2 on 2024-12-07 13:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='SourceSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='api.document')),
            ],
        ),
        migrations.CreateModel(
            name='TargetSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='api.sourcesegment')),
            ],
        ),
    ]
