# Generated by Django 4.2 on 2024-12-14 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sourcesegment',
            old_name='source',
            new_name='text',
        ),
    ]
