# Generated by Django 4.2 on 2024-12-14 14:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_source_sourcesegment_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index', models.IntegerField()),
                ('source', models.TextField()),
                ('lang', models.CharField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='api.document')),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target', models.TextField()),
                ('lang', models.CharField()),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='api.segment')),
            ],
        ),
        migrations.RemoveField(
            model_name='targetsegment',
            name='source',
        ),
        migrations.DeleteModel(
            name='SourceSegment',
        ),
        migrations.DeleteModel(
            name='TargetSegment',
        ),
    ]
