# Generated by Django 4.2 on 2024-12-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_document_id_sourcesegment_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetsegment',
            name='text',
            field=models.TextField(default=15),
            preserve_default=False,
        ),
    ]
