# Generated by Django 4.2 on 2024-12-06 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_targetsegment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetsegment',
            name='source',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.sourcesegment'),
        ),
    ]
