# Generated by Django 4.2 on 2024-12-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_segment_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='index',
            field=models.IntegerField(),
        ),
    ]
