# Generated by Django 4.2 on 2025-01-08 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_segment_index'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='segment',
            unique_together={('document', 'index')},
        ),
    ]
